name: (Prod) Node.js Checker

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  node:
    name: Node Build
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    strategy:
      max-parallel: 4
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          architecture: x64

      - name: Install dependencies
        run: |
          npm ci --audit=false
        
      - name: Build
        run: |
          cp .env.example .env
          npm run build:prod

      - name: Install devDependencies
        run: |
          npm install --production=false --audit=false 

      - name: Linter
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test:coverage

      - name: Update Codecov (coverage)
        if: ${{ success() }}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./coverage/clover.xml
